# Project 0 - Introduction to Python

In this project, we will guide you through the basics of Python. We will be using Python 3 for all of these projects, and we recommend you use this kernel rather than Python 2 becuase the later version is slowly becoming outdated/discontinued.

## Table of Content:
1. What is Python
2. Expressions
3. Structure
4. Contorls

## 1. What is Python?

Python is a programming language that is arguable one of the most used language for data analysis apart from Matlab and R. Unlike Matlab and R, Python does not come with a lot of built in packages and functions. However, Python does allow you to easily install and import external packages, giving you the flexibility to use other's code with little effort. Python is also an open-source programming language, allowing people to program without any cost and use packages for free! Lastly, Python has many packages for machine learning, data visualization, and statistical analysis growing by the day with a very active community to help you with any questions. Learning this general-purpose programming language will serve you well as you go into the field of research and tech jobs (particular data-science).

We will go through the basics of Python in this project, and by the next project you should be comfortable with writing simple scripts.

## 2. Python Expressions

### 2.1 Numbers
There are 3 types of numbers: integers, float, complex

In [2]:
# integers
1
-1
# float
3.14
2.71
# complex
2+1j

(2+1j)

### 2.2 Strings
Strings are pretty straightforward

In [8]:
"Hello"

'Hello'

### 2.2 Boolean
Booleans are also straightforward. Boolean types can only be one of two things: ```True``` or ```False```

In [41]:
x = True
y = False

### 2.3 Variables
You can store any values in variables for you to reference later. Get in the habit of creating good names for your variables because once the projects get bigger, there will be a lot of variables you will have to reference

In [1]:
# bad names
x1 = 1.3
x1, y1 = 2, 3
_i = 3.15
# good names
number_animals = 10

### 2.4 Arithmetic Operations

You can do simple arithmetics with values in variables or literal numbers. The two arithmetics notation that may be unintuitive is power and remainders. In Python, you can do simple power computation using ```**``` notation (Ex: 2^3 ==> ```2**3```). The other arithmetic is remainder, which you can do by using ```%``` (Ex: Remainder of 3/2 = 1,   ```3%2```). 

In [3]:
# add, subtract
z1 = x + y
z2 = x - y
# multiply, divide
z3 = x * y
z4 = x / y
# power, remainders
z3 = x ** y
z4 = x % y

### 2.5 Functions
There are several built in function for Python. Look [here](https://docs.python.org/3/library/functions.html) to see the full list of all the built in function. One of the most used built-in function you will use is ``` print()```. This funciton will print (SURPRISE!) values inside of variables and other statements in the text stream below the cell you run the operation in. Down below is also an example of a new string formatting syntax if you ever want to print variables along with string statements.

In [6]:
z5 = abs(-3)
z6 = round(2.4)
print(z5)
print(z6)

3
2


In [7]:
print(f"z5 = {z5}")

z5 = 3


### 2.6 Python Modules
Most of the time, you will be implementing your own functions or importing them from other modules. To import packages you will used the  ```import {module}```. One module that you installed with Anaconda is Numpy, a library for numerical arrays and mathematical function. Other modules are Matplotlib and SciPy. Note that not all modules were installed with Anaconda. You will have to separately install some pacakges using ```pip``` and ```conda```, which we will show you how to do when the time comes! For now, most of the packages you will use for the first few projects should come with Anaconda.

In [9]:
import numpy
print(numpy.sqrt(3))

1.7320508075688772


In [11]:
# if you don't like the "long" names of modules you can set your own name
import numpy as np
print(np.sqrt(3))

1.7320508075688772


In [12]:
# maybe you want to import just specific functions within the numpy module
from numpy import sqrt, exp
print(sqrt(3))

1.7320508075688772


In [13]:
# '*' is a wildcard, which tells import command to grab everything in numpy
# NOTE: we would not recommend this since you don't want ALL the functions within a module.
#       It is good practice to only get the functions you need.
from numpy import *

## 3. Structure
### 3.1 Objects
In Python, EVERYTHING is an object (i.e. a combination of data and functions). Yeah! Even numbers (e.g. 1, 4, 6.7). Generally, objects will have attributes (data) and methods (spectialized functions for an object). You can even create your own object! First let me convince you that numbers are objects too by showing that it has a method of its own called ```is_integer```. Once you are convinced that everything is an object, lets create your own object called ```Student```

In [18]:
x = 3.14
x.is_integer() # returns True/False depending on whether x is an integer

False

In [2]:
# Create your own object
class Student:
    age = 18                   # attribute
    def what_is_my_age(self):  # method
        return self.age

student = Student()            # created an instance of an object
print(student.age)
print(student.what_is_my_age())

18
18


In [4]:
class Person:
    def __init__(self, name, age): #__init__ function will be the first function to run
        self.name = name
        self.age = age

p1 = Person("John", 36)
p2 = Person("Susie", 20)
print(f"{p1.name} is {p1.age} years old")
print(f"{p2.name} is {p2.age} years old")
# Note: The __init__() function is called automatically every time the class is being used to create a new object.

John is 36 years old
Susie is 20 years old


### 3.2 Lists, Tuples, and Arrays
The beauty of computer is that you can compute everything in batches. Therefore, we have lists, tuples, and arrays that puts numbers together and compute things in batches. Most of the time you will use Numpy Arrays, but knowing how to use lists and tuples will also be important later on. What's the difference?
* **List:** list is mutable, as in you can change what is inside the list after you create it.
* **Tuple:** tuple is immutable, as in you CANNOT change what is inside the list after you create it.
* **Array:** array is mutable like list. It is essential a list but with added benefits like methods and quick search.
Fun Fact: String is actually a tuple of char (```"hello"``` == ```('h','e','l','l','o')```). Therefore, once you create a string, you cannot change the string.

In [9]:
### Tuples
x = (2,3,4)
# x[1] = 6
# x.append(4)

In [10]:
### Strings
x = "hello"
# x[0] = 'c'

In [15]:
### Lists
x_list = [1,2,3]
# x[0] = 5

In [17]:
import numpy as np
### Arrays
x_array = np.array([1,2,3]) # just wrap a list with the np.array function
x_array.shape               # arrays have attributes and methods lists do not
# x_list.shape

(3,)

### 3.3 More Arrays
When you create an array with a single row of numbers, that is just a one-dimensional array. What if you have an array of an array? Well, that creates a two-dimensional array, also called matrix. In general, we call any array with dimension higher than one a matrix. These high dimensional arrays are really where arrays shine over list.

In [25]:
# one-dimensional arrays
x = np.zeros(3)
y = np.ones(3)
z = np.arange(0,10,2)
print(x)
print(y)
print(z)

[0. 0. 0.]
[1. 1. 1.]
[0 2 4 6 8]


In [22]:
# matrix
x = np.zeros((3,3))
y = np.ones((3,3))
print(x)
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Wait! If arrays are mutable, then shouldn't we be able to edit these arrays/matrix? YES! This is how you can access specific numbers or slice of numbers:

**Note: In Python, everything starts with index 0**

In [27]:
z = np.arange(0,10,1)
print(z)
print(z[2])        # index to the 3 element in array z

[0 1 2 3 4 5 6 7 8 9]
2


In [40]:
z_rand = np.random.randint(5, size=(3,3))
print(z_rand)
print(z_rand[0,:])
print(z_rand[:,0])
z_rand[0,:] = 0    # LOOK! arrays are mutable
print(z_rand)

[[2 4 1]
 [0 4 1]
 [3 1 1]]
[2 4 1]
[2 0 3]
[[0 0 0]
 [0 4 1]
 [3 1 1]]


## 4. Controls
Everything we have learned is great, but if we are going do simple one line computation, then we could just use a calculator. The real power of computers are their ability to compute many different instructions depending on various condition. This is where logic comes in, allowing you to automate certain task and compute things that would take years to do with you own hand. Here you will learn ```if```, ```for```, and ```while``` statements

### 4.1: if statements
You use ```if``` statements if you want certain block of code to run only under certain conditions. If the condition is not met, you can run another block of code using ```else``` statement. For example:

**Note: the else statemnt must follow the if statement**

In [44]:
x = 2
y = 3
if x < 3:
    print("x is less than 3")
if y > 5:
    print("y is greater than 5")
else:
    print("y is not greater than 5")

x is less than 3
y is not greater than 5


### 4.2: for statements
```for``` loops allow you to iterate over a block of code so that you don't have to copy and paste the code multiple times. This is very useful when working with arrays as you will see below.

In [45]:
for i in range(10):
    print("imagine having to write this print statment 10 times!")

imagine having to write this print statment 10 times!
imagine having to write this print statment 10 times!
imagine having to write this print statment 10 times!
imagine having to write this print statment 10 times!
imagine having to write this print statment 10 times!
imagine having to write this print statment 10 times!
imagine having to write this print statment 10 times!
imagine having to write this print statment 10 times!
imagine having to write this print statment 10 times!
imagine having to write this print statment 10 times!


In [49]:
x_array = np.arange(1,10)
print(x_array)
for x in x_array:
    print(x)

[1 2 3 4 5 6 7 8 9]
1
2
3
4
5
6
7
8
9


### 4.3: while statements
```for``` loop is great if you know when the loop should end. However, sometimes you may want a certain block of code to run until you get a certain output:

In [51]:
x = 5
while x > 0:
    print(x)
    x = x - 1
    # keeps iterating over this block of code until x is greater than 0

5
4
3
2
1


<hr>
<center><h1>Reference</h1></center>

* "A Student's Guide to Python for Physical Modeling" - Jesse Kinder and Philip Nelson